In [75]:
import numpy as np
#U = np.array([[5., 2., 1.], [0, 1., -1.], [0, 0, 3.]]).astype(np.float64)
# U = np.array([[5., 2., 1.,-4], [0, 1., -1.,-3], [0, 0, 3.,2], [0, 0, -0,2.1]]).astype(np.float64)
#print('U=',U)
#b = np.ones(U.shape[0])
#L = U.transpose()
#print('L=',L)
#print("b=",b)
#x = backward(U,b)   
#print("\n backward residual:",np.linalg.norm(U@x-b))
#x = forward(L,b)   
#print("\n forward residual:",np.linalg.norm(L@x-b))

A = np.array([[2,4,3,5], [-4,-7,-5,-8], [6,8,2,9], [4,9,-2,14]]).astype(np.float64)

#A = np.random.rand(3,3)
#b = np.random.rand(3)
print('A=',A)
print("b=",b)

print("\n----------")

def lu_factors(Mat):
    n = Mat.shape[0]
    L = np.eye(n)
    U = np.copy(Mat)
    print("L=",L)
    for i in range(n):
        print("i=",i)
        lji = U[i+1:, i] / U[i, i]
        L[i+1:, i] = lji
        print("column factor", lji)
        print("U[i] = ", U[i])
        for j in range(i+1, U.shape[0]):
            print("j=",j)
            U[j] -= lji[j-(i+1)] * U[i]
    return L,U

def backward(Mat,rhs):
    n = len(rhs)
    sol = np.zeros(n)
    sol[-1] = rhs[-1]/Mat[-1,-1]
    # looping over rows in reverse 
    # 0 1 2 - we want to have 1 and then 0
    for i in range(n-2, -1, -1): # start stop step
        #print("\ni:",i)
        #print("Mat[i,i+1:]:",Mat[i,i+1:])
        sol[i] = (rhs[i] - np.dot(Mat[i,i+1:], sol[i+1:]))/Mat[i,i]
    return sol

def forward(Mat,rhs):
    n = len(rhs)
    sol = np.zeros(n)
    sol[0] = rhs[0]/Mat[0,0]
    for i in range(1, n, 1): # start stop step
        #print("\ni:",i)
        #print("Mat[i,:i]:",Mat[i,:i])
        sol[i] = (rhs[i] - np.dot(Mat[i,:i], sol[:i]))/Mat[i,i]
    return sol

print(A)
L, U = lu_factors(A)
#print("L=",L)
#print("U=",U)
print("residual = ",np.linalg.norm(L@U - A))

A= [[ 2.  4.  3.  5.]
 [-4. -7. -5. -8.]
 [ 6.  8.  2.  9.]
 [ 4.  9. -2. 14.]]
b= [0.7866491  0.96180468 0.11921558]

----------
[[ 2.  4.  3.  5.]
 [-4. -7. -5. -8.]
 [ 6.  8.  2.  9.]
 [ 4.  9. -2. 14.]]
L= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
i= 0
column factor [-2.  3.  2.]
U[i] =  [2. 4. 3. 5.]
j= 1
j= 2
j= 3
i= 1
column factor [-4.  1.]
U[i] =  [0. 1. 1. 2.]
j= 2
j= 3
i= 2
column factor [3.]
U[i] =  [ 0.  0. -3.  2.]
j= 3
i= 3
column factor []
U[i] =  [ 0.  0.  0. -4.]
residual =  0.0


In [100]:

A = np.array([[1.,3.],[1.,-1]])
print("A=",A)


def qr_decomposition(Mat):
    n = A.shape[0]
    Q = np.zeros_like(Mat)
    R = np.zeros_like(Mat)
    for i in range(n):
        print("--------\ni=",i)
        # original vector
        ai = Mat[:,i]
        # initialize
        ai_90 = ai
        # remove projections from previous vectors
        for j in range(i):
            print("j=",j)
            qj = Q[:,j]
            ai_90 -= np.dot(ai,qj)*qj
            R[j,i] = np.dot(ai,qj)
        
        print("ai_90 = ", ai_90)        
        ai_90_norm = np.linalg.norm(ai_90)
        qi = ai_90/ai_90_norm
        print("qi = ", qi)
        R[i,i] = ai_90_norm
        Q[:,i] = qi
    
    return Q, R

Q,R = qr_decomposition(A)
print("Q=",Q)
print("R=",R)

print("\n",1/np.sqrt(2))
            
        
        

A= [[ 1.  3.]
 [ 1. -1.]]
--------
i= 0
ai_90 =  [1. 1.]
qi =  [0.70710678 0.70710678]
--------
i= 1
j= 0
ai_90 =  [ 2. -2.]
qi =  [ 0.70710678 -0.70710678]
Q= [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
R= [[1.41421356e+00 2.22044605e-16]
 [0.00000000e+00 2.82842712e+00]]

 0.7071067811865475
