In [13]:
import numpy as np
from LU_decomposition import back_substitution

def getQ(M):
    Q = []
    M = np.transpose(M)

    for i in range(len(M)):
        v = np.copy(M[i,:]) # i-th column of A
        for j in range(i):
            v -= (np.dot(M[i,:], Q[j]) / np.dot(Q[j], Q[j])) * Q[j]
        Q.append(v)
    
    Q = np.array(Q) / np.linalg.norm(Q, axis=1, keepdims=True)
    Q = Q.transpose()

    return Q

def getR(M, Q):
    # R = Q^T A 
    Q_t = np.transpose(Q)
    return Q_t@M

A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
#A = np.array([[6, 3], [3, 6], [4, 5], [8, 1]])
A = A.astype(float)
print(A)
b = np.array([32., 23., 33., 31.])

# get QR decompositon
Q = getQ(A)
R = getR(A, Q)
print(Q)
print(R)

# solve linear system
rhs = np.dot(np.transpose(Q), b)
x = back_substitution(R, rhs) # upper triangular ==> BS
print("Solution from QR:", x)

# compare with reference solution
x_ref = np.linalg.solve(A.T @ A, A.T @ b)
print("Reference solution:", x_ref)

print('QR error is:',np.linalg.norm(x_ref-x)/np.linalg.norm(x_ref))

[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]
[[ 0.53665631 -0.01164445 -0.53083247 -0.65580584]
 [ 0.26832816  0.72195591 -0.37863574  0.51323935]
 [ 0.35777088  0.47742246  0.73871091 -0.31364627]
 [ 0.71554175 -0.50071136  0.1707573   0.45621276]]
[[ 1.11803399e+01  5.72433402e+00  1.20747671e+01  2.49545186e+01]
 [ 0.00000000e+00  6.18320305e+00  4.83244683e+00 -8.54702644e+00]
 [-1.77635684e-15  5.55111512e-17  4.56590162e+00  4.81461334e+00]
 [-4.44089210e-15 -3.49720253e-15 -6.66133815e-16  4.47658770e+00]]
Solution from QR: [ 5.84854919 -0.67374381  2.14012739 -1.20382166]
Reference solution: [ 5.84854919 -0.67374381  2.14012739 -1.20382166]
QR error is: 3.740242889193505e-15
