In [4]:
import numpy as np

A = np.array([[5, 2, 1], [0, 1, -1], [0, 0, 3]]).astype(np.float64)
#A = np.triu(np.random.rand(5*5).reshape(5,5)).astype(np.float64)
print("matrix:\n", A)

n = A.shape[1]
b = np.ones(n)
print("rhs:", b)
print(A[2:])

matrix:
 [[ 5.  2.  1.]
 [ 0.  1. -1.]
 [ 0.  0.  3.]]
rhs: [1. 1. 1.]
[[0. 0. 3.]]


In [2]:
def solveUpTri(Mat,rhs):
    
    print("Solver begins ! \n")
    if not np.allclose(Mat, np.triu(Mat)):
        raise Exception("The matrix is not upper triangular !")
    n = len(rhs)
    #Allocating space for the solution vector
    sol = np.zeros(n)
    #Initializing back-substitution with the last row.
    sol[-1] = rhs[-1] / Mat[-1,-1] # assign last value
    print("initial  x[", n-1 ,"]: ", sol[-1], "\n")
    #Looping over rows in reverse (from the bottom up), 
    #starting with the second to last row, because the 
    #last row solve was completed in the last step.
    for i in range(n-2, -1, -1): # range(start, stop, step)
        print(""\n"i)
        print("dot prod:", Mat[i,i+1:], " with ", sol[i+1:])
        sol[i] = ( rhs[i] - np.dot(Mat[i,i+1:], sol[i+1:]) ) / Mat[i,i]
        print("value of x[", i, "]: ", sol[i], "\n")
    print("\nDone solving ! \n")
    return sol

In [5]:
x = solveUpTri(A,b)
print("Residual:", np.abs(A@x - b) )

Solver begins ! 

initial  x[ 2 ]:  0.3333333333333333 

1
dot prod: [-1.]  with  [0.33333333]
value of x[ 1 ]:  1.3333333333333333 

0
dot prod: [2. 1.]  with  [1.33333333 0.33333333]
value of x[ 0 ]:  -0.4 


Done solving ! 

Residual: [2.22044605e-16 0.00000000e+00 0.00000000e+00]
